name: main-build

#this drops to nuget

on:
  push:

  workflow_dispatch:

jobs:
  buildOnWindows:
    name: Build on Windows
    env:
      NUPKG_MAJOR: 1.0.
      BASE: 8
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build and Pack Reloadify3000
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=$NUPKG_MAJOR$MINOR_VERSION-beta
          echo "PACKAGE VERSION: $VERSION"
          dotnet build -c Release -p:Version=$VERSION Reloadify3000.Build/Reloadify3000.Build.Tasks.csproj
          dotnet build -c Release -p:Version=$VERSION Reloadify3000/Reloadify3000.csproj

      - uses: actions/upload-artifact@v6
        name: Upload Nuget Artifact
        with:
          name: nuget-artifact
          path: |
            **/*.nupkg
            **/*.snupkg
            **/*.symbols.nupkg